<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="5" passed="2" failed="2" skipped="1">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-03-05T13:41:00 IST" name="Suite" finished-at="2024-03-05T13:41:41 IST" duration-ms="41018">
    <groups>
      <group name="ErrorHandling">
        <method signature="ErrorValidationTest.loginValidation()[pri:0, instance:AnupamTesting.SeleniumFramework.tests.ErrorValidationTest@11392934]" name="loginValidation" class="AnupamTesting.SeleniumFramework.tests.ErrorValidationTest"/>
        <method signature="ErrorValidationTest.productValidation()[pri:0, instance:AnupamTesting.SeleniumFramework.tests.ErrorValidationTest@11392934]" name="productValidation" class="AnupamTesting.SeleniumFramework.tests.ErrorValidationTest"/>
      </group> <!-- ErrorHandling -->
      <group name="Purchase">
        <method signature="SubmitOrderTest.submitOrder(java.util.HashMap)[pri:0, instance:AnupamTesting.SeleniumFramework.tests.SubmitOrderTest@36916eb0]" name="submitOrder" class="AnupamTesting.SeleniumFramework.tests.SubmitOrderTest"/>
      </group> <!-- Purchase -->
    </groups>
    <test started-at="2024-03-05T13:41:00 IST" name="Error Validation Test" finished-at="2024-03-05T13:41:38 IST" duration-ms="38165">
      <class name="AnupamTesting.SeleniumFramework.tests.ErrorValidationTest">
        <test-method is-config="true" signature="lunchApplication()[pri:0, instance:AnupamTesting.SeleniumFramework.tests.ErrorValidationTest@11392934]" started-at="2024-03-05T13:41:00 IST" name="lunchApplication" finished-at="2024-03-05T13:41:04 IST" duration-ms="3755" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- lunchApplication -->
        <test-method signature="loginValidation()[pri:0, instance:AnupamTesting.SeleniumFramework.tests.ErrorValidationTest@11392934]" started-at="2024-03-05T13:41:04 IST" name="loginValidation" finished-at="2024-03-05T13:41:05 IST" duration-ms="877" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:AnupamTesting.SeleniumFramework.tests.ErrorValidationTest@11392934]" started-at="2024-03-05T13:41:05 IST" name="tearDown" finished-at="2024-03-05T13:41:08 IST" duration-ms="3072" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="lunchApplication()[pri:0, instance:AnupamTesting.SeleniumFramework.tests.ErrorValidationTest@11392934]" started-at="2024-03-05T13:41:08 IST" name="lunchApplication" finished-at="2024-03-05T13:41:12 IST" duration-ms="3972" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- lunchApplication -->
        <test-method signature="productValidation()[pri:0, instance:AnupamTesting.SeleniumFramework.tests.ErrorValidationTest@11392934]" started-at="2024-03-05T13:41:12 IST" name="productValidation" finished-at="2024-03-05T13:41:35 IST" duration-ms="23153" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:644)
at AnupamTesting.SeleniumFramework.tests.ErrorValidationTest.productValidation(ErrorValidationTest.java:50)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- productValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:AnupamTesting.SeleniumFramework.tests.ErrorValidationTest@11392934]" started-at="2024-03-05T13:41:35 IST" name="tearDown" finished-at="2024-03-05T13:41:38 IST" duration-ms="3062" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- AnupamTesting.SeleniumFramework.tests.ErrorValidationTest -->
    </test> <!-- Error Validation Test -->
    <test started-at="2024-03-05T13:41:00 IST" name="Submit Order Test" finished-at="2024-03-05T13:41:41 IST" duration-ms="41018">
      <class name="AnupamTesting.SeleniumFramework.tests.SubmitOrderTest">
        <test-method is-config="true" signature="lunchApplication()[pri:0, instance:AnupamTesting.SeleniumFramework.tests.SubmitOrderTest@36916eb0]" started-at="2024-03-05T13:41:00 IST" name="lunchApplication" finished-at="2024-03-05T13:41:04 IST" duration-ms="3923" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- lunchApplication -->
        <test-method signature="submitOrder(java.util.HashMap)[pri:0, instance:AnupamTesting.SeleniumFramework.tests.SubmitOrderTest@36916eb0]" started-at="2024-03-05T13:41:04 IST" name="submitOrder" data-provider="getData" finished-at="2024-03-05T13:41:18 IST" duration-ms="13835" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Welcome2024, product=ZARA COAT 3, email=anupam@gmail.com}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:AnupamTesting.SeleniumFramework.tests.SubmitOrderTest@36916eb0]" started-at="2024-03-05T13:41:18 IST" name="tearDown" finished-at="2024-03-05T13:41:21 IST" duration-ms="3063" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="lunchApplication()[pri:0, instance:AnupamTesting.SeleniumFramework.tests.SubmitOrderTest@36916eb0]" started-at="2024-03-05T13:41:21 IST" name="lunchApplication" finished-at="2024-03-05T13:41:25 IST" duration-ms="3465" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- lunchApplication -->
        <test-method signature="submitOrder(java.util.HashMap)[pri:0, instance:AnupamTesting.SeleniumFramework.tests.SubmitOrderTest@36916eb0]" started-at="2024-03-05T13:41:25 IST" name="submitOrder" data-provider="getData" finished-at="2024-03-05T13:41:38 IST" duration-ms="13265" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Welcome2024, product=ADIDAS ORIGINAL, email=anupam@gmail.com}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at AnupamTesting.SeleniumFramework.tests.SubmitOrderTest.submitOrder(SubmitOrderTest.java:50)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:AnupamTesting.SeleniumFramework.tests.SubmitOrderTest@36916eb0]" started-at="2024-03-05T13:41:38 IST" name="tearDown" finished-at="2024-03-05T13:41:41 IST" duration-ms="3084" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method signature="orderHistory()[pri:0, instance:AnupamTesting.SeleniumFramework.tests.SubmitOrderTest@36916eb0]" started-at="2024-03-05T13:41:41 IST" name="orderHistory" finished-at="2024-03-05T13:41:41 IST" depends-on-methods="AnupamTesting.SeleniumFramework.tests.SubmitOrderTest.submitOrder" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method AnupamTesting.SeleniumFramework.tests.SubmitOrderTest.orderHistory() on instance AnupamTesting.SeleniumFramework.tests.SubmitOrderTest@36916eb0 depends on not successfully finished methods 
[AnupamTesting.SeleniumFramework.tests.SubmitOrderTest.submitOrder() on instance AnupamTesting.SeleniumFramework.tests.SubmitOrderTest@36916eb0]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method AnupamTesting.SeleniumFramework.tests.SubmitOrderTest.orderHistory() on instance AnupamTesting.SeleniumFramework.tests.SubmitOrderTest@36916eb0 depends on not successfully finished methods 
[AnupamTesting.SeleniumFramework.tests.SubmitOrderTest.submitOrder() on instance AnupamTesting.SeleniumFramework.tests.SubmitOrderTest@36916eb0]
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:157)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- orderHistory -->
      </class> <!-- AnupamTesting.SeleniumFramework.tests.SubmitOrderTest -->
    </test> <!-- Submit Order Test -->
  </suite> <!-- Suite -->
</testng-results>
